const musicas = [
    // --- NACIONAIS ---
    { nome: "Evidências", artista: "Chitãozinho & Xororó", emocoes: ["Paixao", "Nostalgia", "Tristeza", "Ansiedade", "Angustia"] },
    { nome: "Anunciação", artista: "Alceu Valença", emocoes: ["Felicidade", "Esperanca", "Nostalgia", "Calma", "Gratidao"] },
    { nome: "O Sol", artista: "Vitor Kley", emocoes: ["Felicidade", "Calma", "Gratidao", "Esperanca", "Motivacao"] },
    { nome: "Pais e Filhos", artista: "Legião Urbana", emocoes: ["Nostalgia", "Angustia", "Tristeza", "Ansiedade", "Frustracao"] },
    { nome: "Sentadão", artista: "Pedro Sampaio", emocoes: ["Felicidade", "Motivacao", "Paixao"] },
    { nome: "Gaiola É O Troco", artista: "MC Du Black", emocoes: ["Motivacao", "Raiva", "Frustracao", "Aversao"] },
    { nome: "Evoluiu", artista: "MC Kevin o Chris", emocoes: ["Felicidade", "Motivacao", "Nostalgia"] },
    { nome: "Hit Contagiante", artista: "Felipe Original", emocoes: ["Felicidade", "Motivacao", "Ansiedade"] },
    { nome: "Sapequinha", artista: "Eduardo Costa", emocoes: ["Paixao", "Felicidade", "Ciume", "Motivacao"] },
    { nome: "Deus Me Livre", artista: "Raça Negra", emocoes: ["Paixao", "Nostalgia", "Ansiedade", "Ciume", "Tristeza"] },
    { nome: "Cheia de Manias", artista: "Raça Negra", emocoes: ["Felicidade", "Nostalgia", "Paixao", "Ciume", "Frustracao"] },
    { nome: "Tentativas Em Vão", artista: "Garota Safada", emocoes: ["Tristeza", "Frustracao", "Angustia", "Paixao", "Ciume"] },
    { nome: "Anjo Vagabundo", artista: "Banda Calypso", emocoes: ["Tristeza", "Angustia", "Frustracao", "Paixao", "Ciume"] },
    { nome: "Meu Mel", artista: "Markinhos Moura", emocoes: ["Paixao", "Nostalgia", "Calma", "Tristeza"] },
    { nome: "Acredita", artista: "MC Hariel", emocoes: ["Motivacao", "Esperanca", "Gratidao", "Angustia", "Frustracao"] },
    { nome: "Cracudo", artista: "Teto", emocoes: ["Motivacao", "Ansiedade", "Raiva", "Frustracao"] },
    { nome: "Kenny G", artista: "Matuê", emocoes: ["Motivacao", "Tedio", "Aversao", "Ansiedade"] },
    { nome: "Vampiro", artista: "Matuê, WIU, Teto", emocoes: ["Motivacao", "Ansiedade", "Tedio", "Paixao"] },
    { nome: "A Cura", artista: "Lulu Santos", emocoes: ["Esperanca", "Calma", "Gratidao", "Felicidade", "Nostalgia"] },
    { nome: "Como Nossos Pais", artista: "Elis Regina", emocoes: ["Angustia", "Frustracao", "Nostalgia", "Raiva", "Tristeza"] },
    { nome: "Tempo Perdido", artista: "Legião Urbana", emocoes: ["Nostalgia", "Angustia", "Calma", "Tristeza", "Frustracao"] },
    { nome: "Medo Bobo", artista: "Maiara & Maraisa", emocoes: ["Paixao", "Ansiedade", "Felicidade", "Esperanca", "Ciume"] },
    { nome: "Infiel", artista: "Marília Mendonça", emocoes: ["Raiva", "Frustracao", "Ciume", "Tristeza", "Angustia"] },
    { nome: "Ciumera", artista: "Marília Mendonça", emocoes: ["Ciume", "Tristeza", "Frustracao", "Paixao", "Angustia"] },
    { nome: "Supera", artista: "Marília Mendonça", emocoes: ["Motivacao", "Raiva", "Paixao", "Ciume", "Frustracao"] },
    { nome: "Notícia Boa", artista: "Hugo & Guilherme", emocoes: ["Paixao", "Felicidade", "Esperanca", "Ansiedade", "Ciume"] },
    { nome: "O Que É, O Que É?", artista: "Gonzaguinha", emocoes: ["Felicidade", "Esperanca", "Gratidao", "Motivacao", "Nostalgia"] },
    { nome: "Aos Olhos do Pai", artista: "Diante do Trono", emocoes: ["Gratidao", "Calma", "Esperanca", "Felicidade"] },
    { nome: "Raridade", artista: "Anderson Freire", emocoes: ["Gratidao", "Esperanca", "Calma", "Motivacao"] },
    { nome: "Girassol", artista: "Priscilla Alcantara & Whindersson Nunes", emocoes: ["Calma", "Gratidao", "Esperanca", "Tristeza", "Nostalgia"] },
    { nome: "Construção", artista: "Chico Buarque", emocoes: ["Angustia", "Aversao", "Tristeza", "Frustracao", "Raiva"] },
    { nome: "Cálice", artista: "Chico Buarque", emocoes: ["Raiva", "Angustia", "Aversao", "Frustracao", "Ansiedade"] },
    { nome: "Amarelo", artista: "Emicida", emocoes: ["Motivacao", "Esperanca", "Gratidao", "Angustia", "Felicidade"] },
    { nome: "Capítulo 4, Versículo 3", artista: "Racionais MC's", emocoes: ["Raiva", "Angustia", "Aversao", "Frustracao", "Ansiedade"] },
    { nome: "Negro Drama", artista: "Racionais MC's", emocoes: ["Angustia", "Raiva", "Motivacao", "Frustracao", "Gratidao"] },
    { nome: "Vaca Profana", artista: "Gal Costa", emocoes: ["Nostalgia", "Aversao", "Felicidade", "Motivacao"] },
    { nome: "Fogo E Paixão", artista: "Wando", emocoes: ["Paixao", "Nostalgia", "Felicidade", "Ansiedade", "Ciume"] },
    { nome: "A Dança do Vampiro", artista: "Asa de Águia", emocoes: ["Felicidade", "Nostalgia", "Motivacao"] },
    { nome: "Ilariê", artista: "Xuxa", emocoes: ["Felicidade", "Nostalgia", "Motivacao"] },
    { nome: "Anna Júlia", artista: "Los Hermanos", emocoes: ["Paixao", "Frustracao", "Nostalgia", "Ansiedade", "Ciume"] },
    { nome: "Pro Dia Nascer Feliz", artista: "Barão Vermelho", emocoes: ["Motivacao", "Felicidade", "Paixao", "Nostalgia"] },
    { nome: "Malandragem", artista: "Cássia Eller", emocoes: ["Frustracao", "Tedio", "Angustia", "Nostalgia", "Ansiedade"] },
    { nome: "A Sombra da Maldade", artista: "Cidade Negra", emocoes: ["Calma", "Nostalgia", "Paixao", "Tristeza"] },
    { nome: "Vira-Vira", artista: "Mamonas Assassinas", emocoes: ["Felicidade", "Nostalgia", "Aversao"] },
    { nome: "Pelados em Santos", artista: "Mamonas Assassinas", emocoes: ["Felicidade", "Paixao", "Nostalgia", "Ansiedade"] },
    { nome: "A Última Dança", artista: "Link do Zap", emocoes: ["Felicidade"] },
    { nome: "Coisas Que Eu Sei", artista: "Jorge Vercillo", emocoes: ["Tristeza", "Nostalgia"] },
    { nome: "Sozinho", artista: "Caetano Veloso", emocoes: ["Tristeza", "Angustia"] },
    { nome: "A Noite", artista: "Tiê", emocoes: ["Tristeza", "Angustia"] },
    { nome: "Era Óbvio", artista: "Marisa Monte", emocoes: ["Paixao"] },
    { nome: "No Escuro", artista: "ANAVITORIA", emocoes: ["Paixao", "Angustia"] },
    { nome: "Palpite", artista: "Vanessa Rangel", emocoes: ["Paixao", "Nostalgia"] },
    { nome: "Beija Eu", artista: "Marisa Monte", emocoes: ["Paixao"] },
    { nome: "Maria, Maria", artista: "Milton Nascimento", emocoes: ["Motivacao", "Nostalgia"] },
    { nome: "Terra Prometida", artista: "João Gomes", emocoes: ["Motivacao"] },
    { nome: "Sonho", artista: "Atitude 67", emocoes: ["Motivacao", "Felicidade"] },
    { nome: "Lindo Balão Azul", artista: "Guilherme Arantes", emocoes: ["Nostalgia", "Felicidade"] },
    { nome: "Aquarela", artista: "Toquinho", emocoes: ["Nostalgia", "Tristeza"] },

    // --- INTERNACIONAIS ---
    { nome: "Bohemian Rhapsody", artista: "Queen", emocoes: ["Angustia", "Ansiedade", "Nostalgia", "Tristeza", "Raiva"] },
    { nome: "Don't Stop Believin'", artista: "Journey", emocoes: ["Esperanca", "Motivacao", "Felicidade", "Nostalgia"] },
    { nome: "Eye of the Tiger", artista: "Survivor", emocoes: ["Motivacao", "Raiva", "Esperanca", "Ansiedade"] },
    { nome: "Happy", artista: "Pharrell Williams", emocoes: ["Felicidade", "Motivacao", "Gratidao"] },
    { nome: "Count on Me", artista: "Bruno Mars", emocoes: ["Calma", "Gratidao", "Felicidade", "Esperanca"] },
    { nome: "Fix You", artista: "Coldplay", emocoes: ["Tristeza", "Esperanca", "Calma", "Angustia", "Gratidao"] },
    { nome: "Viva La Vida", artista: "Coldplay", emocoes: ["Motivacao", "Felicidade", "Nostalgia", "Angustia", "Frustracao"] },
    { nome: "Someone Like You", artista: "Adele", emocoes: ["Tristeza", "Angustia", "Nostalgia", "Paixao", "Ciume"] },
    { nome: "Rolling in the Deep", artista: "Adele", emocoes: ["Raiva", "Frustracao", "Paixao", "Ciume", "Angustia"] },
    { nome: "Hello", artista: "Adele", emocoes: ["Tristeza", "Nostalgia", "Angustia", "Frustracao", "Ansiedade"] },
    { nome: "Shape of You", artista: "Ed Sheeran", emocoes: ["Paixao", "Felicidade", "Ansiedade", "Motivacao"] },
    { nome: "Perfect", artista: "Ed Sheeran", emocoes: ["Paixao", "Calma", "Felicidade", "Gratidao"] },
    { nome: "Bad Guy", artista: "Billie Eilish", emocoes: ["Aversao", "Tedio", "Ansiedade", "Raiva"] },
    { nome: "Lovely", artista: "Billie Eilish & Khalid", emocoes: ["Tristeza", "Ansiedade", "Angustia", "Frustracao", "Calma"] },
    { nome: "Lucid Dreams", artista: "Juice WRLD", emocoes: ["Tristeza", "Angustia", "Frustracao", "Paixao", "Ciume"] },
    { nome: "SICKO MODE", artista: "Travis Scott", emocoes: ["Motivacao", "Ansiedade", "Raiva"] },
    { nome: "HUMBLE.", artista: "Kendrick Lamar", emocoes: ["Raiva", "Motivacao", "Aversao"] },
    { nome: "God's Plan", artista: "Drake", emocoes: ["Gratidao", "Motivacao", "Esperanca", "Felicidade"] },
    { nome: "Hotline Bling", artista: "Drake", emocoes: ["Ciume", "Frustracao", "Tristeza", "Nostalgia", "Paixao"] },
    { nome: "Blinding Lights", artista: "The Weeknd", emocoes: ["Ansiedade", "Motivacao", "Nostalgia", "Paixao", "Tristeza"] },
    { nome: "Starboy", artista: "The Weeknd", emocoes: ["Motivacao", "Aversao", "Raiva"] },
    { nome: "Smells Like Teen Spirit", artista: "Nirvana", emocoes: ["Raiva", "Tedio", "Aversao", "Angustia", "Frustracao"] },
    { nome: "In the End", artista: "Linkin Park", emocoes: ["Frustracao", "Angustia", "Raiva", "Tristeza", "Ansiedade"] },
    { nome: "Numb", artista: "Linkin Park", emocoes: ["Angustia", "Frustracao", "Raiva", "Aversao", "Ansiedade"] },
    { nome: "Sweet Child O' Mine", artista: "Guns N' Roses", emocoes: ["Paixao", "Nostalgia", "Felicidade", "Motivacao"] },
    { nome: "Hotel California", artista: "Eagles", emocoes: ["Nostalgia", "Ansiedade", "Angustia", "Tedio"] },
    { nome: "Imagine", artista: "John Lennon", emocoes: ["Calma", "Esperanca", "Gratidao"] },
    { nome: "Let It Be", artista: "The Beatles", emocoes: ["Calma", "Esperanca", "Gratidao", "Nostalgia"] },
    { nome: "Hey Jude", artista: "The Beatles", emocoes: ["Ansiedade", "Motivacao", "Esperanca", "Calma", "Gratidao"] },
    { nome: "Wonderwall", artista: "Oasis", emocoes: ["Nostalgia", "Calma", "Paixao", "Esperanca"] },
    { nome: "Creep", artista: "Radiohead", emocoes: ["Angustia", "Frustracao", "Aversao", "Tristeza", "Ciume"] },
    { nome: "Stressed Out", artista: "Twenty One Pilots", emocoes: ["Ansiedade", "Nostalgia", "Tedio", "Frustracao", "Angustia"] },
    { nome: "Drivers License", artista: "Olivia Rodrigo", emocoes: ["Tristeza", "Ciume", "Angustia", "Frustracao", "Paixao"] },
    { nome: "Good 4 U", artista: "Olivia Rodrigo", emocoes: ["Raiva", "Frustracao", "Ciume", "Aversao", "Ansiedade"] },
    { nome: "As It Was", artista: "Harry Styles", emocoes: ["Nostalgia", "Felicidade", "Tristeza", "Calma", "Ansiedade"] },
    { nome: "Watermelon Sugar", artista: "Harry Styles", emocoes: ["Felicidade", "Paixao", "Nostalgia"] },
    { nome: "Uptown Funk", artista: "Mark Ronson ft. Bruno Mars", emocoes: ["Felicidade", "Motivacao"] },
    { nome: "Can't Stop the Feeling!", artista: "Justin Timberlake", emocoes: ["Felicidade", "Motivacao", "Gratidao"] },
    { nome: "Shallow", artista: "Lady Gaga & Bradley Cooper", emocoes: ["Paixao", "Angustia", "Esperanca", "Ansiedade", "Tristeza"] },
    { nome: "Bad Romance", artista: "Lady Gaga", emocoes: ["Paixao", "Ansiedade", "Raiva", "Frustracao"] },
    { nome: "Believer", artista: "Imagine Dragons", emocoes: ["Motivacao", "Raiva", "Angustia", "Esperanca"] },
    { nome: "Radioactive", artista: "Imagine Dragons", emocoes: ["Ansiedade", "Motivacao", "Raiva", "Esperanca"] },
    { nome: "Unstoppable", artista: "Sia", emocoes: ["Motivacao", "Esperanca", "Felicidade"] },
    { nome: "Chandelier", artista: "Sia", emocoes: ["Angustia", "Ansiedade", "Frustracao", "Tristeza"] },
    { nome: "Despacito", artista: "Luis Fonsi ft. Daddy Yankee", emocoes: ["Felicidade", "Paixao", "Ansiedade"] },
    { nome: "Beautiful Life", artista: "Now United", emocoes: ["Felicidade"] },
    { nome: "Accidentally in Love", artista: "Counting Crows", emocoes: ["Felicidade", "Paixao"] },
    { nome: "Dancing Queen", artista: "ABBA", emocoes: ["Felicidade", "Nostalgia"] },
    { nome: "Girls Just Want to Have Fun", artista: "Cyndi Lauper", emocoes: ["Felicidade"] },
    { nome: "The Night We Met", artista: "Lord Huron", emocoes: ["Tristeza", "Nostalgia"] },
    { nome: "Another Love", artista: "Tom Odell", emocoes: ["Tristeza", "Angustia"] },
    { nome: "Sailor Song", artista: "Gigi Perez", emocoes: ["Tristeza", "Paixao"] },
    { nome: "All I Want", artista: "Olivia Rodrigo & High School", emocoes: ["Tristeza", "Angustia"] },
    { nome: "Unsaid Emily", artista: "Charlie Gillespie & Julie and the Phantoms Cast", emocoes: ["Tristeza", "Angustia", "Nostalgia"] },
    { nome: "The Archer", artista: "Taylor Swift", emocoes: ["Tristeza", "Ansiedade"] },
    { nome: "GONE, GONE / THANK YOU", artista: "Tyler, The Creator", emocoes: ["Tristeza", "Angustia"] },
    { nome: "Matilda", artista: "Harry Styles", emocoes: ["Tristeza", "Nostalgia"] },
    { nome: "Purple Rain", artista: "Prince & The Revolution", emocoes: ["Tristeza", "Nostalgia"] },
    { nome: "Lovers", artista: "Anna of the North", emocoes: ["Paixao", "Felicidade"] },
    { nome: "Iris", artista: "The Goo Goo Dolls", emocoes: ["Paixao", "Angustia"] },
    { nome: "So American", artista: "Olivia Rodrigo", emocoes: ["Paixao", "Felicidade"] },
    { nome: "Obsessed", artista: "Olivia Rodrigo", emocoes: ["Ciumes", "Raiva"] },
    { nome: "All Of The Girls You Loved Before", artista: "Taylor Swift", emocoes: ["Ciumes", "Paixao"] },
    { nome: "Linger", artista: "The Cranberries", emocoes: ["Ciumes", "Tristeza", "Angustia"] },
    { nome: "7 Years", artista: "Lukas Graham", emocoes: ["Motivacao", "Nostalgia"] },
    { nome: "Vienna", artista: "Billy Joel", emocoes: ["Motivacao", "Ansiedade"] },
    { nome: "93 Million Miles", artista: "Jason Mraz", emocoes: ["Motivacao", "Felicidade"] },
    { nome: "Billionaire", artista: "Travie McCoy feat. Bruno Mars", emocoes: ["Motivacao", "Felicidade"] },
    { nome: "Hall of Fame", artista: "The Script feat. will.i.am", emocoes: ["Motivacao"] },
    { nome: "Better Than Revenge", artista: "Taylor Swift", emocoes: ["Raiva", "Ciumes"] },
    { nome: "brutal", artista: "Olivia Rodrigo", emocoes: ["Raiva", "Ansiedade"] },
    { nome: "all-american bitch", artista: "Olivia Rodrigo", emocoes: ["Raiva", "Ansiedade"] },
    { nome: "Forever Young", artista: "Alphaville", emocoes: ["Nostalgia"] },
    { nome: "Heroes", artista: "David Bowie", emocoes: ["Nostalgia", "Motivacao"] },
    { nome: "Under Pressure", artista: "Queen & David Bowie", emocoes: ["Nostalgia", "Ansiedade"] },
    { nome: "Let Her Go", artista: "Passenger", emocoes: ["Nostalgia", "Tristeza"] }
];